package cn.luoyulingfeng.dbindexresearch.model;

import cn.luoyulingfeng.dbindexresearch.util.DateTimeUtil;

import java.text.SimpleDateFormat;
import java.util.Date;

public class BookBorrowRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_borrow.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_borrow.person_no
     *
     * @mbggenerated
     */
    private String personNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_borrow.person_type
     *
     * @mbggenerated
     */
    private Integer personType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_borrow.book_id
     *
     * @mbggenerated
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_borrow.borrow_time
     *
     * @mbggenerated
     */
    private Date borrowTime;

    public BookBorrowRecord() {
    }

    public BookBorrowRecord(Integer id, String personNo, Integer personType, Integer bookId, Date borrowTime) {
        this.id = id;
        this.personNo = personNo;
        this.personType = personType;
        this.bookId = bookId;
        this.borrowTime = borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_borrow.id
     *
     * @return the value of wj_book_borrow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_borrow.id
     *
     * @param id the value for wj_book_borrow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_borrow.person_no
     *
     * @return the value of wj_book_borrow.person_no
     *
     * @mbggenerated
     */
    public String getPersonNo() {
        return personNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_borrow.person_no
     *
     * @param personNo the value for wj_book_borrow.person_no
     *
     * @mbggenerated
     */
    public void setPersonNo(String personNo) {
        this.personNo = personNo == null ? null : personNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_borrow.person_type
     *
     * @return the value of wj_book_borrow.person_type
     *
     * @mbggenerated
     */
    public Integer getPersonType() {
        return personType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_borrow.person_type
     *
     * @param personType the value for wj_book_borrow.person_type
     *
     * @mbggenerated
     */
    public void setPersonType(Integer personType) {
        this.personType = personType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_borrow.book_id
     *
     * @return the value of wj_book_borrow.book_id
     *
     * @mbggenerated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_borrow.book_id
     *
     * @param bookId the value for wj_book_borrow.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_borrow.borrow_time
     *
     * @return the value of wj_book_borrow.borrow_time
     *
     * @mbggenerated
     */
    public Date getBorrowTime() {
        return borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_borrow.borrow_time
     *
     * @param borrowTime the value for wj_book_borrow.borrow_time
     *
     * @mbggenerated
     */
    public void setBorrowTime(Date borrowTime) {
        this.borrowTime = borrowTime;
    }

    @Override
    public String toString() {
        return id + "," + personNo + "," + personType + "," + bookId + "," + DateTimeUtil.format(borrowTime);
    }
}