package cn.luoyulingfeng.dbindexresearch.model;

import cn.luoyulingfeng.dbindexresearch.util.DateTimeUtil;

import java.util.Date;

public class BookReturnRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_return.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_return.person_no
     *
     * @mbggenerated
     */
    private String personNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_return.person_type
     *
     * @mbggenerated
     */
    private Integer personType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_return.book_id
     *
     * @mbggenerated
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book_return.return_time
     *
     * @mbggenerated
     */
    private Date returnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_return.id
     *
     * @return the value of wj_book_return.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_return.id
     *
     * @param id the value for wj_book_return.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_return.person_no
     *
     * @return the value of wj_book_return.person_no
     *
     * @mbggenerated
     */
    public String getPersonNo() {
        return personNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_return.person_no
     *
     * @param personNo the value for wj_book_return.person_no
     *
     * @mbggenerated
     */
    public void setPersonNo(String personNo) {
        this.personNo = personNo == null ? null : personNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_return.person_type
     *
     * @return the value of wj_book_return.person_type
     *
     * @mbggenerated
     */
    public Integer getPersonType() {
        return personType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_return.person_type
     *
     * @param personType the value for wj_book_return.person_type
     *
     * @mbggenerated
     */
    public void setPersonType(Integer personType) {
        this.personType = personType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_return.book_id
     *
     * @return the value of wj_book_return.book_id
     *
     * @mbggenerated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_return.book_id
     *
     * @param bookId the value for wj_book_return.book_id
     *
     * @mbggenerated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book_return.return_time
     *
     * @return the value of wj_book_return.return_time
     *
     * @mbggenerated
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book_return.return_time
     *
     * @param returnTime the value for wj_book_return.return_time
     *
     * @mbggenerated
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }

    @Override
    public String toString() {
        return id + "," + personNo + "," + personType + "," + bookId + "," + DateTimeUtil.format(returnTime);
    }
}