package cn.luoyulingfeng.dbindexresearch.model;

import java.util.ArrayList;
import java.util.List;

public class BookExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public BookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIsNull() {
            addCriterion("book_isbn is null");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIsNotNull() {
            addCriterion("book_isbn is not null");
            return (Criteria) this;
        }

        public Criteria andBookIsbnEqualTo(String value) {
            addCriterion("book_isbn =", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotEqualTo(String value) {
            addCriterion("book_isbn <>", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnGreaterThan(String value) {
            addCriterion("book_isbn >", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnGreaterThanOrEqualTo(String value) {
            addCriterion("book_isbn >=", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLessThan(String value) {
            addCriterion("book_isbn <", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLessThanOrEqualTo(String value) {
            addCriterion("book_isbn <=", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnLike(String value) {
            addCriterion("book_isbn like", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotLike(String value) {
            addCriterion("book_isbn not like", value, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnIn(List<String> values) {
            addCriterion("book_isbn in", values, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotIn(List<String> values) {
            addCriterion("book_isbn not in", values, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnBetween(String value1, String value2) {
            addCriterion("book_isbn between", value1, value2, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookIsbnNotBetween(String value1, String value2) {
            addCriterion("book_isbn not between", value1, value2, "bookIsbn");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoIsNull() {
            addCriterion("book_bookcase_no is null");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoIsNotNull() {
            addCriterion("book_bookcase_no is not null");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoEqualTo(String value) {
            addCriterion("book_bookcase_no =", value, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoNotEqualTo(String value) {
            addCriterion("book_bookcase_no <>", value, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoGreaterThan(String value) {
            addCriterion("book_bookcase_no >", value, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoGreaterThanOrEqualTo(String value) {
            addCriterion("book_bookcase_no >=", value, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoLessThan(String value) {
            addCriterion("book_bookcase_no <", value, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoLessThanOrEqualTo(String value) {
            addCriterion("book_bookcase_no <=", value, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoLike(String value) {
            addCriterion("book_bookcase_no like", value, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoNotLike(String value) {
            addCriterion("book_bookcase_no not like", value, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoIn(List<String> values) {
            addCriterion("book_bookcase_no in", values, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoNotIn(List<String> values) {
            addCriterion("book_bookcase_no not in", values, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoBetween(String value1, String value2) {
            addCriterion("book_bookcase_no between", value1, value2, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookBookcaseNoNotBetween(String value1, String value2) {
            addCriterion("book_bookcase_no not between", value1, value2, "bookBookcaseNo");
            return (Criteria) this;
        }

        public Criteria andBookNameCnIsNull() {
            addCriterion("book_name_cn is null");
            return (Criteria) this;
        }

        public Criteria andBookNameCnIsNotNull() {
            addCriterion("book_name_cn is not null");
            return (Criteria) this;
        }

        public Criteria andBookNameCnEqualTo(String value) {
            addCriterion("book_name_cn =", value, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnNotEqualTo(String value) {
            addCriterion("book_name_cn <>", value, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnGreaterThan(String value) {
            addCriterion("book_name_cn >", value, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnGreaterThanOrEqualTo(String value) {
            addCriterion("book_name_cn >=", value, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnLessThan(String value) {
            addCriterion("book_name_cn <", value, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnLessThanOrEqualTo(String value) {
            addCriterion("book_name_cn <=", value, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnLike(String value) {
            addCriterion("book_name_cn like", value, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnNotLike(String value) {
            addCriterion("book_name_cn not like", value, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnIn(List<String> values) {
            addCriterion("book_name_cn in", values, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnNotIn(List<String> values) {
            addCriterion("book_name_cn not in", values, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnBetween(String value1, String value2) {
            addCriterion("book_name_cn between", value1, value2, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameCnNotBetween(String value1, String value2) {
            addCriterion("book_name_cn not between", value1, value2, "bookNameCn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnIsNull() {
            addCriterion("book_name_en is null");
            return (Criteria) this;
        }

        public Criteria andBookNameEnIsNotNull() {
            addCriterion("book_name_en is not null");
            return (Criteria) this;
        }

        public Criteria andBookNameEnEqualTo(String value) {
            addCriterion("book_name_en =", value, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnNotEqualTo(String value) {
            addCriterion("book_name_en <>", value, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnGreaterThan(String value) {
            addCriterion("book_name_en >", value, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("book_name_en >=", value, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnLessThan(String value) {
            addCriterion("book_name_en <", value, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnLessThanOrEqualTo(String value) {
            addCriterion("book_name_en <=", value, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnLike(String value) {
            addCriterion("book_name_en like", value, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnNotLike(String value) {
            addCriterion("book_name_en not like", value, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnIn(List<String> values) {
            addCriterion("book_name_en in", values, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnNotIn(List<String> values) {
            addCriterion("book_name_en not in", values, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnBetween(String value1, String value2) {
            addCriterion("book_name_en between", value1, value2, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookNameEnNotBetween(String value1, String value2) {
            addCriterion("book_name_en not between", value1, value2, "bookNameEn");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIsNull() {
            addCriterion("book_author is null");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIsNotNull() {
            addCriterion("book_author is not null");
            return (Criteria) this;
        }

        public Criteria andBookAuthorEqualTo(String value) {
            addCriterion("book_author =", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotEqualTo(String value) {
            addCriterion("book_author <>", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorGreaterThan(String value) {
            addCriterion("book_author >", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("book_author >=", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLessThan(String value) {
            addCriterion("book_author <", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLessThanOrEqualTo(String value) {
            addCriterion("book_author <=", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorLike(String value) {
            addCriterion("book_author like", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotLike(String value) {
            addCriterion("book_author not like", value, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorIn(List<String> values) {
            addCriterion("book_author in", values, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotIn(List<String> values) {
            addCriterion("book_author not in", values, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorBetween(String value1, String value2) {
            addCriterion("book_author between", value1, value2, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookAuthorNotBetween(String value1, String value2) {
            addCriterion("book_author not between", value1, value2, "bookAuthor");
            return (Criteria) this;
        }

        public Criteria andBookPressIsNull() {
            addCriterion("book_press is null");
            return (Criteria) this;
        }

        public Criteria andBookPressIsNotNull() {
            addCriterion("book_press is not null");
            return (Criteria) this;
        }

        public Criteria andBookPressEqualTo(String value) {
            addCriterion("book_press =", value, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressNotEqualTo(String value) {
            addCriterion("book_press <>", value, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressGreaterThan(String value) {
            addCriterion("book_press >", value, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressGreaterThanOrEqualTo(String value) {
            addCriterion("book_press >=", value, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressLessThan(String value) {
            addCriterion("book_press <", value, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressLessThanOrEqualTo(String value) {
            addCriterion("book_press <=", value, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressLike(String value) {
            addCriterion("book_press like", value, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressNotLike(String value) {
            addCriterion("book_press not like", value, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressIn(List<String> values) {
            addCriterion("book_press in", values, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressNotIn(List<String> values) {
            addCriterion("book_press not in", values, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressBetween(String value1, String value2) {
            addCriterion("book_press between", value1, value2, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookPressNotBetween(String value1, String value2) {
            addCriterion("book_press not between", value1, value2, "bookPress");
            return (Criteria) this;
        }

        public Criteria andBookVersionIsNull() {
            addCriterion("book_version is null");
            return (Criteria) this;
        }

        public Criteria andBookVersionIsNotNull() {
            addCriterion("book_version is not null");
            return (Criteria) this;
        }

        public Criteria andBookVersionEqualTo(Integer value) {
            addCriterion("book_version =", value, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionNotEqualTo(Integer value) {
            addCriterion("book_version <>", value, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionGreaterThan(Integer value) {
            addCriterion("book_version >", value, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_version >=", value, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionLessThan(Integer value) {
            addCriterion("book_version <", value, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionLessThanOrEqualTo(Integer value) {
            addCriterion("book_version <=", value, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionIn(List<Integer> values) {
            addCriterion("book_version in", values, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionNotIn(List<Integer> values) {
            addCriterion("book_version not in", values, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionBetween(Integer value1, Integer value2) {
            addCriterion("book_version between", value1, value2, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("book_version not between", value1, value2, "bookVersion");
            return (Criteria) this;
        }

        public Criteria andBookPriceIsNull() {
            addCriterion("book_price is null");
            return (Criteria) this;
        }

        public Criteria andBookPriceIsNotNull() {
            addCriterion("book_price is not null");
            return (Criteria) this;
        }

        public Criteria andBookPriceEqualTo(Float value) {
            addCriterion("book_price =", value, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceNotEqualTo(Float value) {
            addCriterion("book_price <>", value, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceGreaterThan(Float value) {
            addCriterion("book_price >", value, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("book_price >=", value, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceLessThan(Float value) {
            addCriterion("book_price <", value, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceLessThanOrEqualTo(Float value) {
            addCriterion("book_price <=", value, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceIn(List<Float> values) {
            addCriterion("book_price in", values, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceNotIn(List<Float> values) {
            addCriterion("book_price not in", values, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceBetween(Float value1, Float value2) {
            addCriterion("book_price between", value1, value2, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookPriceNotBetween(Float value1, Float value2) {
            addCriterion("book_price not between", value1, value2, "bookPrice");
            return (Criteria) this;
        }

        public Criteria andBookSeriesIsNull() {
            addCriterion("book_series is null");
            return (Criteria) this;
        }

        public Criteria andBookSeriesIsNotNull() {
            addCriterion("book_series is not null");
            return (Criteria) this;
        }

        public Criteria andBookSeriesEqualTo(String value) {
            addCriterion("book_series =", value, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesNotEqualTo(String value) {
            addCriterion("book_series <>", value, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesGreaterThan(String value) {
            addCriterion("book_series >", value, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesGreaterThanOrEqualTo(String value) {
            addCriterion("book_series >=", value, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesLessThan(String value) {
            addCriterion("book_series <", value, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesLessThanOrEqualTo(String value) {
            addCriterion("book_series <=", value, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesLike(String value) {
            addCriterion("book_series like", value, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesNotLike(String value) {
            addCriterion("book_series not like", value, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesIn(List<String> values) {
            addCriterion("book_series in", values, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesNotIn(List<String> values) {
            addCriterion("book_series not in", values, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesBetween(String value1, String value2) {
            addCriterion("book_series between", value1, value2, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookSeriesNotBetween(String value1, String value2) {
            addCriterion("book_series not between", value1, value2, "bookSeries");
            return (Criteria) this;
        }

        public Criteria andBookCoverIsNull() {
            addCriterion("book_cover is null");
            return (Criteria) this;
        }

        public Criteria andBookCoverIsNotNull() {
            addCriterion("book_cover is not null");
            return (Criteria) this;
        }

        public Criteria andBookCoverEqualTo(String value) {
            addCriterion("book_cover =", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverNotEqualTo(String value) {
            addCriterion("book_cover <>", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverGreaterThan(String value) {
            addCriterion("book_cover >", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverGreaterThanOrEqualTo(String value) {
            addCriterion("book_cover >=", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverLessThan(String value) {
            addCriterion("book_cover <", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverLessThanOrEqualTo(String value) {
            addCriterion("book_cover <=", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverLike(String value) {
            addCriterion("book_cover like", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverNotLike(String value) {
            addCriterion("book_cover not like", value, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverIn(List<String> values) {
            addCriterion("book_cover in", values, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverNotIn(List<String> values) {
            addCriterion("book_cover not in", values, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverBetween(String value1, String value2) {
            addCriterion("book_cover between", value1, value2, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookCoverNotBetween(String value1, String value2) {
            addCriterion("book_cover not between", value1, value2, "bookCover");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageIsNull() {
            addCriterion("book_total_page is null");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageIsNotNull() {
            addCriterion("book_total_page is not null");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageEqualTo(Integer value) {
            addCriterion("book_total_page =", value, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageNotEqualTo(Integer value) {
            addCriterion("book_total_page <>", value, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageGreaterThan(Integer value) {
            addCriterion("book_total_page >", value, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_total_page >=", value, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageLessThan(Integer value) {
            addCriterion("book_total_page <", value, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageLessThanOrEqualTo(Integer value) {
            addCriterion("book_total_page <=", value, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageIn(List<Integer> values) {
            addCriterion("book_total_page in", values, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageNotIn(List<Integer> values) {
            addCriterion("book_total_page not in", values, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageBetween(Integer value1, Integer value2) {
            addCriterion("book_total_page between", value1, value2, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookTotalPageNotBetween(Integer value1, Integer value2) {
            addCriterion("book_total_page not between", value1, value2, "bookTotalPage");
            return (Criteria) this;
        }

        public Criteria andBookStatusIsNull() {
            addCriterion("book_status is null");
            return (Criteria) this;
        }

        public Criteria andBookStatusIsNotNull() {
            addCriterion("book_status is not null");
            return (Criteria) this;
        }

        public Criteria andBookStatusEqualTo(Integer value) {
            addCriterion("book_status =", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusNotEqualTo(Integer value) {
            addCriterion("book_status <>", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusGreaterThan(Integer value) {
            addCriterion("book_status >", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_status >=", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusLessThan(Integer value) {
            addCriterion("book_status <", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusLessThanOrEqualTo(Integer value) {
            addCriterion("book_status <=", value, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusIn(List<Integer> values) {
            addCriterion("book_status in", values, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusNotIn(List<Integer> values) {
            addCriterion("book_status not in", values, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusBetween(Integer value1, Integer value2) {
            addCriterion("book_status between", value1, value2, "bookStatus");
            return (Criteria) this;
        }

        public Criteria andBookStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("book_status not between", value1, value2, "bookStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wj_book
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wj_book
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}