package cn.luoyulingfeng.dbindexresearch.model;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_isbn
     *
     * @mbggenerated
     */
    private String bookIsbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_bookcase_no
     *
     * @mbggenerated
     */
    private String bookBookcaseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_name_cn
     *
     * @mbggenerated
     */
    private String bookNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_name_en
     *
     * @mbggenerated
     */
    private String bookNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_author
     *
     * @mbggenerated
     */
    private String bookAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_press
     *
     * @mbggenerated
     */
    private String bookPress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_version
     *
     * @mbggenerated
     */
    private Integer bookVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_price
     *
     * @mbggenerated
     */
    private Float bookPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_series
     *
     * @mbggenerated
     */
    private String bookSeries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_cover
     *
     * @mbggenerated
     */
    private String bookCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_total_page
     *
     * @mbggenerated
     */
    private Integer bookTotalPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_book.book_status
     *
     * @mbggenerated
     */
    private Integer bookStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.id
     *
     * @return the value of wj_book.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.id
     *
     * @param id the value for wj_book.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_isbn
     *
     * @return the value of wj_book.book_isbn
     *
     * @mbggenerated
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_isbn
     *
     * @param bookIsbn the value for wj_book.book_isbn
     *
     * @mbggenerated
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn == null ? null : bookIsbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_bookcase_no
     *
     * @return the value of wj_book.book_bookcase_no
     *
     * @mbggenerated
     */
    public String getBookBookcaseNo() {
        return bookBookcaseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_bookcase_no
     *
     * @param bookBookcaseNo the value for wj_book.book_bookcase_no
     *
     * @mbggenerated
     */
    public void setBookBookcaseNo(String bookBookcaseNo) {
        this.bookBookcaseNo = bookBookcaseNo == null ? null : bookBookcaseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_name_cn
     *
     * @return the value of wj_book.book_name_cn
     *
     * @mbggenerated
     */
    public String getBookNameCn() {
        return bookNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_name_cn
     *
     * @param bookNameCn the value for wj_book.book_name_cn
     *
     * @mbggenerated
     */
    public void setBookNameCn(String bookNameCn) {
        this.bookNameCn = bookNameCn == null ? null : bookNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_name_en
     *
     * @return the value of wj_book.book_name_en
     *
     * @mbggenerated
     */
    public String getBookNameEn() {
        return bookNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_name_en
     *
     * @param bookNameEn the value for wj_book.book_name_en
     *
     * @mbggenerated
     */
    public void setBookNameEn(String bookNameEn) {
        this.bookNameEn = bookNameEn == null ? null : bookNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_author
     *
     * @return the value of wj_book.book_author
     *
     * @mbggenerated
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_author
     *
     * @param bookAuthor the value for wj_book.book_author
     *
     * @mbggenerated
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_press
     *
     * @return the value of wj_book.book_press
     *
     * @mbggenerated
     */
    public String getBookPress() {
        return bookPress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_press
     *
     * @param bookPress the value for wj_book.book_press
     *
     * @mbggenerated
     */
    public void setBookPress(String bookPress) {
        this.bookPress = bookPress == null ? null : bookPress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_version
     *
     * @return the value of wj_book.book_version
     *
     * @mbggenerated
     */
    public Integer getBookVersion() {
        return bookVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_version
     *
     * @param bookVersion the value for wj_book.book_version
     *
     * @mbggenerated
     */
    public void setBookVersion(Integer bookVersion) {
        this.bookVersion = bookVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_price
     *
     * @return the value of wj_book.book_price
     *
     * @mbggenerated
     */
    public Float getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_price
     *
     * @param bookPrice the value for wj_book.book_price
     *
     * @mbggenerated
     */
    public void setBookPrice(Float bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_series
     *
     * @return the value of wj_book.book_series
     *
     * @mbggenerated
     */
    public String getBookSeries() {
        return bookSeries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_series
     *
     * @param bookSeries the value for wj_book.book_series
     *
     * @mbggenerated
     */
    public void setBookSeries(String bookSeries) {
        this.bookSeries = bookSeries == null ? null : bookSeries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_cover
     *
     * @return the value of wj_book.book_cover
     *
     * @mbggenerated
     */
    public String getBookCover() {
        return bookCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_cover
     *
     * @param bookCover the value for wj_book.book_cover
     *
     * @mbggenerated
     */
    public void setBookCover(String bookCover) {
        this.bookCover = bookCover == null ? null : bookCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_total_page
     *
     * @return the value of wj_book.book_total_page
     *
     * @mbggenerated
     */
    public Integer getBookTotalPage() {
        return bookTotalPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_total_page
     *
     * @param bookTotalPage the value for wj_book.book_total_page
     *
     * @mbggenerated
     */
    public void setBookTotalPage(Integer bookTotalPage) {
        this.bookTotalPage = bookTotalPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_book.book_status
     *
     * @return the value of wj_book.book_status
     *
     * @mbggenerated
     */
    public Integer getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_book.book_status
     *
     * @param bookStatus the value for wj_book.book_status
     *
     * @mbggenerated
     */
    public void setBookStatus(Integer bookStatus) {
        this.bookStatus = bookStatus;
    }

    @Override
    public String toString() {
        return id + "," + bookIsbn + "," + bookBookcaseNo + "," + bookNameCn + "," + bookNameEn + "," + bookAuthor + "," + bookPress + "," + bookVersion
                + "," + bookPrice + "," + bookSeries + "," + bookCover + "," + bookTotalPage + "," + bookStatus;
    }
}