package cn.luoyulingfeng.dbindexresearch.model;

import cn.luoyulingfeng.dbindexresearch.util.DateTimeUtil;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_no
     *
     * @mbggenerated
     */
    private String stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_name
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_gender
     *
     * @mbggenerated
     */
    private Integer stuGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_age
     *
     * @mbggenerated
     */
    private Integer stuAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_major
     *
     * @mbggenerated
     */
    private String stuMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_type
     *
     * @mbggenerated
     */
    private Integer stuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_grade
     *
     * @mbggenerated
     */
    private Integer stuGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_class
     *
     * @mbggenerated
     */
    private Integer stuClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_student.stu_admission_date
     *
     * @mbggenerated
     */
    private Date stuAdmissionDate;

    public Student() {
    }

    public Student(Integer id, String stuNo, String stuName, Integer stuGender, Integer stuAge, String stuMajor, Integer stuType, Integer stuGrade, Integer stuClass, Date stuAdmissionDate) {
        this.id = id;
        this.stuNo = stuNo;
        this.stuName = stuName;
        this.stuGender = stuGender;
        this.stuAge = stuAge;
        this.stuMajor = stuMajor;
        this.stuType = stuType;
        this.stuGrade = stuGrade;
        this.stuClass = stuClass;
        this.stuAdmissionDate = stuAdmissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.id
     *
     * @return the value of wj_student.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.id
     *
     * @param id the value for wj_student.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_no
     *
     * @return the value of wj_student.stu_no
     *
     * @mbggenerated
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_no
     *
     * @param stuNo the value for wj_student.stu_no
     *
     * @mbggenerated
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo == null ? null : stuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_name
     *
     * @return the value of wj_student.stu_name
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_name
     *
     * @param stuName the value for wj_student.stu_name
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_gender
     *
     * @return the value of wj_student.stu_gender
     *
     * @mbggenerated
     */
    public Integer getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_gender
     *
     * @param stuGender the value for wj_student.stu_gender
     *
     * @mbggenerated
     */
    public void setStuGender(Integer stuGender) {
        this.stuGender = stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_age
     *
     * @return the value of wj_student.stu_age
     *
     * @mbggenerated
     */
    public Integer getStuAge() {
        return stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_age
     *
     * @param stuAge the value for wj_student.stu_age
     *
     * @mbggenerated
     */
    public void setStuAge(Integer stuAge) {
        this.stuAge = stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_major
     *
     * @return the value of wj_student.stu_major
     *
     * @mbggenerated
     */
    public String getStuMajor() {
        return stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_major
     *
     * @param stuMajor the value for wj_student.stu_major
     *
     * @mbggenerated
     */
    public void setStuMajor(String stuMajor) {
        this.stuMajor = stuMajor == null ? null : stuMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_type
     *
     * @return the value of wj_student.stu_type
     *
     * @mbggenerated
     */
    public Integer getStuType() {
        return stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_type
     *
     * @param stuType the value for wj_student.stu_type
     *
     * @mbggenerated
     */
    public void setStuType(Integer stuType) {
        this.stuType = stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_grade
     *
     * @return the value of wj_student.stu_grade
     *
     * @mbggenerated
     */
    public Integer getStuGrade() {
        return stuGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_grade
     *
     * @param stuGrade the value for wj_student.stu_grade
     *
     * @mbggenerated
     */
    public void setStuGrade(Integer stuGrade) {
        this.stuGrade = stuGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_class
     *
     * @return the value of wj_student.stu_class
     *
     * @mbggenerated
     */
    public Integer getStuClass() {
        return stuClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_class
     *
     * @param stuClass the value for wj_student.stu_class
     *
     * @mbggenerated
     */
    public void setStuClass(Integer stuClass) {
        this.stuClass = stuClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_student.stu_admission_date
     *
     * @return the value of wj_student.stu_admission_date
     *
     * @mbggenerated
     */
    public Date getStuAdmissionDate() {
        return stuAdmissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_student.stu_admission_date
     *
     * @param stuAdmissionDate the value for wj_student.stu_admission_date
     *
     * @mbggenerated
     */
    public void setStuAdmissionDate(Date stuAdmissionDate) {
        this.stuAdmissionDate = stuAdmissionDate;
    }

    @Override
    public String toString() {
        return id + "," + stuNo + "," + stuName + "," + stuGender + "," + stuAge + "," + stuMajor + "," + stuType + "," + stuGrade + "," + stuClass + "," + DateTimeUtil.format(stuAdmissionDate);
    }
}