package cn.luoyulingfeng.dbindexresearch.model;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_teacher.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_teacher.tea_no
     *
     * @mbggenerated
     */
    private String teaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_teacher.tea_name
     *
     * @mbggenerated
     */
    private String teaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wj_teacher.tea_college
     *
     * @mbggenerated
     */
    private String teaCollege;

    public Teacher() {
    }

    public Teacher(Integer id, String teaNo, String teaName, String teaCollege) {
        this.id = id;
        this.teaNo = teaNo;
        this.teaName = teaName;
        this.teaCollege = teaCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_teacher.id
     *
     * @return the value of wj_teacher.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_teacher.id
     *
     * @param id the value for wj_teacher.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_teacher.tea_no
     *
     * @return the value of wj_teacher.tea_no
     *
     * @mbggenerated
     */
    public String getTeaNo() {
        return teaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_teacher.tea_no
     *
     * @param teaNo the value for wj_teacher.tea_no
     *
     * @mbggenerated
     */
    public void setTeaNo(String teaNo) {
        this.teaNo = teaNo == null ? null : teaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_teacher.tea_name
     *
     * @return the value of wj_teacher.tea_name
     *
     * @mbggenerated
     */
    public String getTeaName() {
        return teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_teacher.tea_name
     *
     * @param teaName the value for wj_teacher.tea_name
     *
     * @mbggenerated
     */
    public void setTeaName(String teaName) {
        this.teaName = teaName == null ? null : teaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wj_teacher.tea_college
     *
     * @return the value of wj_teacher.tea_college
     *
     * @mbggenerated
     */
    public String getTeaCollege() {
        return teaCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wj_teacher.tea_college
     *
     * @param teaCollege the value for wj_teacher.tea_college
     *
     * @mbggenerated
     */
    public void setTeaCollege(String teaCollege) {
        this.teaCollege = teaCollege == null ? null : teaCollege.trim();
    }

    @Override
    public String toString() {
        return id + "," + teaNo + "," + teaName + "," + teaCollege;
    }
}