package cn.luoyulingfeng.dbindexresearch.mapper;

import cn.luoyulingfeng.dbindexresearch.model.BookBorrowRecord;
import cn.luoyulingfeng.dbindexresearch.model.BookBorrowRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


public interface BookBorrowRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_borrow
     *
     * @mbggenerated
     */
    int countByExample(BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_borrow
     *
     * @mbggenerated
     */
    int deleteByExample(BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_borrow
     *
     * @mbggenerated
     */
    int insert(BookBorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_borrow
     *
     * @mbggenerated
     */
    int insertSelective(BookBorrowRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_borrow
     *
     * @mbggenerated
     */
    List<BookBorrowRecord> selectByExample(BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_borrow
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookBorrowRecord record, @Param("example") BookBorrowRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_borrow
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookBorrowRecord record, @Param("example") BookBorrowRecordExample example);
}