package cn.luoyulingfeng.dbindexresearch.mapper;

import cn.luoyulingfeng.dbindexresearch.model.BookReturnRecord;
import cn.luoyulingfeng.dbindexresearch.model.BookReturnRecordExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


public interface BookReturnRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_return
     *
     * @mbggenerated
     */
    int countByExample(BookReturnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_return
     *
     * @mbggenerated
     */
    int deleteByExample(BookReturnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_return
     *
     * @mbggenerated
     */
    int insert(BookReturnRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_return
     *
     * @mbggenerated
     */
    int insertSelective(BookReturnRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_return
     *
     * @mbggenerated
     */
    List<BookReturnRecord> selectByExample(BookReturnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_return
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BookReturnRecord record, @Param("example") BookReturnRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_book_return
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BookReturnRecord record, @Param("example") BookReturnRecordExample example);
}