package cn.luoyulingfeng.dbindexresearch.mapper;

import cn.luoyulingfeng.dbindexresearch.model.Teacher;
import cn.luoyulingfeng.dbindexresearch.model.TeacherExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_teacher
     *
     * @mbggenerated
     */
    int countByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_teacher
     *
     * @mbggenerated
     */
    int deleteByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_teacher
     *
     * @mbggenerated
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_teacher
     *
     * @mbggenerated
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_teacher
     *
     * @mbggenerated
     */
    List<Teacher> selectByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_teacher
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_teacher
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherExample example);
}